# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2
import meta_pb2 as meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='product_inventory.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17product_inventory.proto\x12\x05proto\x1a\ngogo.proto\x1a\nmeta.proto\"S\n\x1fGetMultiProductInventoryRequest\x12\x0b\n\x03\x61pi\x18\x01 \x01(\t\x12#\n\x0bproduct_ids\x18\x02 \x03(\x05\x42\x0e\xe2\xde\x1f\nProductIDs\"p\n GetMultiProductInventoryResponse\x12\x19\n\x04meta\x18\x01 \x01(\x0b\x32\x0b.proto.Meta\x12\x31\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32#.proto.GetMultiProductInventoryData\"j\n\x1cGetMultiProductInventoryData\x12!\n\nproduct_id\x18\x01 \x01(\x03\x42\r\xe2\xde\x1f\tProductID\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x19.proto.WarehouseInventory\"A\n\x12WarehouseInventory\x12\x16\n\x0ewarehouse_code\x18\x01 \x01(\t\x12\x13\n\x0bqty_salable\x18\x02 \x01(\x05\x32\x88\x01\n\x17ProductInventoryService\x12m\n\x18GetMultiProductInventory\x12&.proto.GetMultiProductInventoryRequest\x1a\'.proto.GetMultiProductInventoryResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[gogo__pb2.DESCRIPTOR,meta__pb2.DESCRIPTOR,])




_GETMULTIPRODUCTINVENTORYREQUEST = _descriptor.Descriptor(
  name='GetMultiProductInventoryRequest',
  full_name='proto.GetMultiProductInventoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='api', full_name='proto.GetMultiProductInventoryRequest.api', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_ids', full_name='proto.GetMultiProductInventoryRequest.product_ids', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\nProductIDs', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=141,
)


_GETMULTIPRODUCTINVENTORYRESPONSE = _descriptor.Descriptor(
  name='GetMultiProductInventoryResponse',
  full_name='proto.GetMultiProductInventoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='proto.GetMultiProductInventoryResponse.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.GetMultiProductInventoryResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=255,
)


_GETMULTIPRODUCTINVENTORYDATA = _descriptor.Descriptor(
  name='GetMultiProductInventoryData',
  full_name='proto.GetMultiProductInventoryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='proto.GetMultiProductInventoryData.product_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\tProductID', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.GetMultiProductInventoryData.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=363,
)


_WAREHOUSEINVENTORY = _descriptor.Descriptor(
  name='WarehouseInventory',
  full_name='proto.WarehouseInventory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouse_code', full_name='proto.WarehouseInventory.warehouse_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qty_salable', full_name='proto.WarehouseInventory.qty_salable', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=430,
)

_GETMULTIPRODUCTINVENTORYRESPONSE.fields_by_name['meta'].message_type = meta__pb2._META
_GETMULTIPRODUCTINVENTORYRESPONSE.fields_by_name['data'].message_type = _GETMULTIPRODUCTINVENTORYDATA
_GETMULTIPRODUCTINVENTORYDATA.fields_by_name['data'].message_type = _WAREHOUSEINVENTORY
DESCRIPTOR.message_types_by_name['GetMultiProductInventoryRequest'] = _GETMULTIPRODUCTINVENTORYREQUEST
DESCRIPTOR.message_types_by_name['GetMultiProductInventoryResponse'] = _GETMULTIPRODUCTINVENTORYRESPONSE
DESCRIPTOR.message_types_by_name['GetMultiProductInventoryData'] = _GETMULTIPRODUCTINVENTORYDATA
DESCRIPTOR.message_types_by_name['WarehouseInventory'] = _WAREHOUSEINVENTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMultiProductInventoryRequest = _reflection.GeneratedProtocolMessageType('GetMultiProductInventoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIPRODUCTINVENTORYREQUEST,
  '__module__' : 'product_inventory_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetMultiProductInventoryRequest)
  })
_sym_db.RegisterMessage(GetMultiProductInventoryRequest)

GetMultiProductInventoryResponse = _reflection.GeneratedProtocolMessageType('GetMultiProductInventoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIPRODUCTINVENTORYRESPONSE,
  '__module__' : 'product_inventory_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetMultiProductInventoryResponse)
  })
_sym_db.RegisterMessage(GetMultiProductInventoryResponse)

GetMultiProductInventoryData = _reflection.GeneratedProtocolMessageType('GetMultiProductInventoryData', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIPRODUCTINVENTORYDATA,
  '__module__' : 'product_inventory_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetMultiProductInventoryData)
  })
_sym_db.RegisterMessage(GetMultiProductInventoryData)

WarehouseInventory = _reflection.GeneratedProtocolMessageType('WarehouseInventory', (_message.Message,), {
  'DESCRIPTOR' : _WAREHOUSEINVENTORY,
  '__module__' : 'product_inventory_pb2'
  # @@protoc_insertion_point(class_scope:proto.WarehouseInventory)
  })
_sym_db.RegisterMessage(WarehouseInventory)


_GETMULTIPRODUCTINVENTORYREQUEST.fields_by_name['product_ids']._options = None
_GETMULTIPRODUCTINVENTORYDATA.fields_by_name['product_id']._options = None

_PRODUCTINVENTORYSERVICE = _descriptor.ServiceDescriptor(
  name='ProductInventoryService',
  full_name='proto.ProductInventoryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=433,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMultiProductInventory',
    full_name='proto.ProductInventoryService.GetMultiProductInventory',
    index=0,
    containing_service=None,
    input_type=_GETMULTIPRODUCTINVENTORYREQUEST,
    output_type=_GETMULTIPRODUCTINVENTORYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTINVENTORYSERVICE)

DESCRIPTOR.services_by_name['ProductInventoryService'] = _PRODUCTINVENTORYSERVICE

# @@protoc_insertion_point(module_scope)
